// Generated by LiveScript 1.3.1
(function(){
  var ldcvNodes, ldrs, ldrsDemo, kit;
  ld$.find(document, '.item').map(function(n){
    return n.addEventListener('click', function(){
      var a, s;
      a = n.getAttribute('data-name');
      s = ld$.find(n, '.square', 0);
      s.classList.remove(a);
      s.offsetHeight;
      return setTimeout(function(){
        return s.classList.add(a);
      }, 0);
    });
  });
  ldcvNodes = ld$.find(document, '.ldcv');
  window.ldcv1 = new ldCover({
    root: ldcvNodes[0]
  });
  window.ldcv2 = new ldCover({
    root: ldcvNodes[1]
  });
  ldrs = new ldSlider({
    root: '.ldrs',
    min: 0,
    max: 1,
    step: 0.01
  });
  ldrsDemo = ld$.find(document, '#ldrs-demo', 0);
  kit = new anikit('bounce');
  return ldrs.on('change', function(it){
    return kit.animateJs(ldrsDemo, it);
  });
})();