// Generated by LiveScript 1.3.1
var easingFit;
easingFit = require('easing-fit');
module.exports = {
  opt: {
    args: [-40]
  },
  step: {
    translateY: function(t){
      return t = (0.25 - Math.abs(Math.pow(t - 0.5, 2))) * 4;
    }
  },
  css: function(opt){
    var ret, this$ = this;
    opt == null && (opt = {});
    ret = easingFit.fit(function(t){
      return this$.step.translateY(t, opt);
    });
    ret = easingFit.toKeyframes(ret, {
      format: 'css',
      propFunc: function(it){
        return ["transform: translate(0," + it.value * opt.args[0] + "px)"];
      },
      name: opt.name || 'bounce-alt'
    });
    return ret;
  },
  js: function(t, opt){
    opt == null && (opt = {});
    t = this.step.translateY(t, opt) * opt.args[0];
    return [1, 0, 0, 1, 0, t];
  },
  glsl: function(opt){
    opt == null && (opt = {});
    return "mat3 " + (opt.name || 'bounceAlt') + "(float t, int type, mat4 opt) {\n  t = t - floor(t);\n  t = (0.25 - pow(abs(t - 0.5), 2.)) * 4. * opt[0][0];\n  mat3 mat = mat3(\n    1., 0., 0,\n    0., 1., 0,\n    0 , t , 1.\n  );\n  return mat;\n}";
  }
};