// Generated by LiveScript 1.3.1
var easingFit, waveform, step;
easingFit = require('easing-fit');
waveform = "M0,50c0,0,2,0.5,6.7,0c5.6-0.6,3.5-18.1,7.1-18.1s4.2,25.6,8.9,25.6s6.8-10.3,8.4-14c1.9-4.4,7.9-5.4,10.9,0.1C46.7,52.3,100,50,100,50";
step = easingFit.stepFromSvg(waveform);
module.exports = {
  name: 'heartbeat',
  css: function(opt){
    var ret;
    opt == null && (opt = {});
    ret = easingFit.fit(function(it){
      return step(it) + 1.0;
    });
    ret = easingFit.toKeyframes(ret, {
      name: opt.name,
      format: 'css',
      propFunc: function(it){
        return ["transform: scale(" + it.value + ")"];
      }
    });
    return ret;
  },
  js: function(t, opt){
    opt == null && (opt = {});
    t = step(t) + 1;
    return [t, 0, 0, t, 0, 0];
  },
  glsl: function(opt){
    opt == null && (opt = {});
    return "float a[5] = float[5](0., 1., 2., 3., 4.);\nmat3 " + (opt.name || 'cycle') + "(float t, int type, mat4 opt) {\n  t = 3.14159 * 2. * (t - floor(t));\n  mat3 mat = mat3(\n    cos(t),  sin(t), 0,\n   -sin(t),  cos(t), 0,\n         0,       0, 1.\n  );\n  return mat;\n}";
  }
};