// Generated by LiveScript 1.3.1
var easingFit, easing;
easingFit = require('easing-fit');
easing = require('../easing');
module.exports = {
  opt: {
    args: [360]
  },
  preset: {
    "spin-fast": {
      opt: {
        args: [1800]
      }
    }
  },
  css: function(opt){
    opt == null && (opt = {});
    return "@keyframes " + opt.name + " {\n  0% { transform: rotate(0deg); animation-timing-function: ease-in-out ; }\n  100% { transform: rotate(" + opt.args[0] + "deg); }\n}";
  },
  js: function(t, opt){
    opt == null && (opt = {});
    t = easing.js.easeInOutQuad(t) * opt.args[0] * Math.PI / 180;
    return [Math.cos(t), Math.sin(t), -Math.sin(t), Math.cos(t), 0, 0];
  },
  glsl: function(opt){
    var ret;
    opt == null && (opt = {});
    ret = easing.glsl.easeInOutQuad + ("mat3 " + (opt.name || 'spin') + "(float t, int type, mat4 opt) {\n  t = easeInOutQuad(t);\n  t = 3.14159 * 2. * (t - floor(t)) * opt[0].x / 360.;\n  mat3 mat = mat3(\n    cos(t),  sin(t), 0,\n   -sin(t),  cos(t), 0,\n         0,       0, 1.\n  );\n  return mat;\n}");
    return ret;
  }
};