// Generated by LiveScript 1.3.1
var ret;
ret = {
  name: 'bounce',
  preset: {
    bounce: {}
  },
  edit: {
    blur: {
      'default': 10,
      type: 'number',
      unit: 'px',
      min: 0,
      max: 100
    },
    unit: {
      'default': 'px',
      type: 'choice',
      values: ["px", "%", ""]
    },
    height: {
      'default': -40,
      type: 'number',
      min: -500,
      max: 500
    },
    offset: {
      'default': 50,
      type: 'number',
      min: -500,
      max: 500
    },
    rate: {
      'default': 13 / 18,
      type: 'number',
      min: 0,
      max: 1
    },
    deflate: {
      'default': 0.6,
      type: 'number',
      min: 0,
      max: 1
    }
  },
  step: function(t, opt){
    var args, y, s;
    opt == null && (opt = {});
    args = [opt.height, opt.offset, opt.rate, opt.deflate];
    if (t < args[2]) {
      t = t / args[2];
      y = args[0] * (0.25 - Math.pow(t - 0.5, 2)) * 4;
      s = 1;
    } else {
      t = (t - args[2]) / (1 - args[2]);
      s = args[3] + (1 - args[3]) * Math.pow(t - 0.5, 2) / 0.25;
      y = args[1] * (1 - s);
    }
    return [1, 0, 0, s, 0, y];
  },
  css: function(opt){
    var optAlt, ret1, ret2, ret, this$ = this;
    optAlt = JSON.parse(JSON.stringify(opt));
    optAlt.height = 1;
    ret1 = easingFit.fit(function(it){
      return this$.step(it, optAlt)[5];
    }, {
      end: opt.rate
    });
    ret2 = easingFit.fit(function(it){
      return this$.step(it, optAlt)[3];
    }, {
      start: opt.rate
    });
    ret1.pop();
    ret = ret1.concat(ret2);
    ret = easingFit.toKeyframes(ret, {
      format: 'css',
      prop: function(f, c, idx){
        var s, y;
        console.log(f, c);
        if (idx < ret1.length) {
          return {
            transform: "translate(0," + f.value * c.height + "px) scaleY(1)"
          };
        } else {
          s = f.value;
          y = (c.offset || 50) * (1 - s);
          return {
            transform: "translate(0," + y + "px) scaleY(" + f.value + ")"
          };
        }
      },
      name: opt.name,
      config: opt
    });
    return ret;
  },
  js: function(t, opt){
    var mat;
    mat = this.step(t, opt);
    return {
      transform: "matrix(" + mat.join(',') + ")"
    };
  },
  affine: function(t, opt){
    var mat;
    mat = this.step(t, opt);
    return {
      transform: [mat[0], mat[1], 0, mat[4], mat[2], mat[3], 0, -mat[5], 0, 0, 1, 0, 0, 0, 0, 1]
    };
  }
};
module.exports = ret;