// Generated by LiveScript 1.3.1
var ret;
ret = {
  name: 'orbit',
  preset: {
    orbit: {
      count: 12,
      radius: 60,
      unit: 'px'
    }
  },
  edit: {
    count: {
      'default': 8,
      type: 'number',
      min: 4,
      max: 36
    },
    radius: {
      'default': 60,
      type: 'number',
      unit: '%',
      min: 0,
      max: 1000
    },
    unit: {
      'default': 'px',
      type: 'choice',
      values: ["px", "%", ""]
    }
  },
  css: function(opt){
    var list, i$, to$, i, r, a, x, y, p;
    list = [];
    for (i$ = 0, to$ = opt.count; i$ <= to$; ++i$) {
      i = i$;
      r = 360 * i / opt.count;
      a = Math.PI * 2 * i / opt.count;
      x = Math.sin(a) * opt.radius;
      y = -Math.cos(a) * opt.radius;
      p = 100 * i / opt.count;
      list.push(" " + p + "% {\nanimation-timing-function: linear;\ntransform: translate(" + x + opt.unit + "," + y + opt.unit + ") rotate(" + r + "deg) } ");
    }
    return " @keyframes " + opt.name + " { " + list.join('\n') + " } ";
  },
  js: function(t, opt){
    var a, x, y, r;
    a = Math.PI * 2 * t;
    x = Math.sin(a) * opt.radius;
    y = -Math.cos(a) * opt.radius;
    r = 360 * t;
    return {
      transform: "translate(" + x + opt.unit + "," + y + opt.unit + ") rotate(" + r + "deg)"
    };
  }
};
module.exports = ret;