// Generated by LiveScript 1.3.1
var easingFit;
easingFit = require('easing-fit');
module.exports = {
  step: {
    rotateZ: function(t){
      var r;
      return r = Math.PI * 2 * (t - Math.floor(t));
    }
  },
  css: function(opts){
    opts == null && (opts = {});
    return "@keyframes " + (opts.name || 'spin') + " {\n  0%,100% { animation-timing-function: linear }\n  0% { transform: rotate(0deg); animation-timing-function: linear }\n  50% { transform: rotate(180deg); animation-timing-function: linear }\n  100% { transform: rotate(360deg); animation-timing-function: linear }\n}";
  },
  js: function(t){
    var r;
    r = this.step.rotateZ(t);
    return [Math.cos(r), Math.sin(r), -Math.sin(r), Math.cos(r), 0, 0];
  },
  glsl: function(opts){
    var ret;
    opts == null && (opts = {});
    ret = "mat3 " + (opts.name || 'spin') + "(float t, int type, mat4 opts) {\n  t = 3.14159 * 2. * (t - floor(t));\n  mat3 mat = mat3(\n    cos(t),  sin(t), 0,\n   -sin(t),  cos(t), 0,\n         0,       0, 1.\n  );\n  return mat;\n}";
    return ret;
  }
};