// Generated by LiveScript 1.3.1
var ret;
ret = {
  name: 'wrench',
  preset: {
    wrench: {}
  },
  edit: {
    dur: {
      'default': 1
    },
    rotate: {
      'default': 45,
      type: 'number',
      min: 0,
      max: 360,
      step: 1
    }
  },
  css: function(opt){
    return "@keyframes " + opt.name + " {\n  20%, 36%, 70%, 86% {\n    transform: rotate(0deg);\n  }\n  0%, 50%, 100% {\n    transform: rotate(" + opt.rotate + "deg);\n  }\n}";
  },
  js: function(t, opt){
    t = (t * 2 - Math.floor(t * 2)) * 0.5;
    if (t < 0.2) {
      t = 1 - t / 0.2;
    } else if (t > 0.36) {
      t = (t - 0.36) / 0.14;
    } else {
      t = 0;
    }
    return {
      transform: "rotate(" + t * opt.rotate + "deg)"
    };
  }
};
module.exports = ret;