// Generated by LiveScript 1.3.1
var spin, bounce;
spin = {
  css: function(){
    return "@keyframes spin {\n  0%,100% { animation-timing-function: linear }\n  0% { transform: rotate(0deg); animation-timing-function: linear }\n  100% { transform: rotate(360deg); animation-timing-function: linear }\n}";
  },
  js: function(t){
    var r, mat;
    r = Math.PI * 2 * (t - Math.floor(t));
    mat = [Math.cos(r), Math.sin(r), -Math.sin(r), Math.cos(r), 0, 0, 0, 0, 1];
    return mat;
  },
  glsl: function(){
    return "mat3 spin(float t) {\n  t = 3.14159 * 2. * (t - floor(t));\n  mat3 mat = mat3(\n    cos(t),  sin(t), 0,\n   -sin(t),  cos(t), 0,\n         0,       0, 1.\n  );\n  return mat;\n}";
  }
};
bounce = {
  css: function(){
    return "@keyframes bounce {\n  0% {\n    transform: translate(0, 0);\n    animation-timing-function: ease-out;\n  }\n  50% {\n    transform: translate(0, -20px);\n    animation-timing-function: ease-in;\n  }\n  100% {\n    transform: translate(0, 0);\n  }\n}";
  },
  js: function(t, opt){
    opt == null && (opt = {});
    t = t - Math.floor(t);
    t = (0.25 - Math.abs(Math.pow(t - 0.5, 2))) * 4 * (opt.height || 1);
    return [1, 0, 0, 1, 0, t];
  },
  glsl: function(){
    return "mat3 bounce(float t, float height) {\n  t = t - floor(t);\n  t = (0.25 - pow(abs(t - 0.5), 2.)) * 4. * height;\n  mat3 mat = mat3(\n    1., 0., 0,\n    0., 1., 0,\n    0 , t , 1.\n  );\n  return mat;\n}";
  }
};