// Generated by LiveScript 1.3.1
var easingFit, spin, bounce, kits, anikit;
easingFit = require('easing-fit');
spin = require('./kits/spin');
bounce = require('./kits/bounce');
kits = {
  spin: spin,
  bounce: bounce
};
anikit = function(name){
  return kits[name];
};
if (typeof window != 'undefined' && window !== null) {
  window.anikit = anikit;
}
module.exports = anikit;