// Generated by LiveScript 1.3.1
var ref$, js, gl, cb, ret;
ref$ = [{}, {}, {}], js = ref$[0], gl = ref$[1], cb = ref$[2];
ret = {
  js: js,
  cb: cb,
  glsl: gl
};
js.linear = function(t){
  return t;
};
cb.linear = function(t){
  return [0.5, 0.5, 0.5, 0.5];
};
gl.linear = 'float linear(float t) { return t; }';
js.easeInOutQuad = function(t){
  if (t < 0.5) {
    return 2 * t * t;
  } else {
    return 4 * t - 2 * t * t - 1;
  }
};
cb.easeInOutQuad = [0.455, 0.03, 0.515, 0.955];
gl.easeInOutQuad = "float easeInOutQuad(float t) { \n  return (t < 0.5 ? 2. * t * t : 4. * t - 2. * t * t - 1.); \n}";
js.easeOutQuad = function(t){
  return t * (2 - t);
};
module.exports = ret;