// Generated by LiveScript 1.3.1
var ldap, tgt, ldcv, popupit;
ldap = new ldAnikitPicker({
  root: '.dropdown',
  defaultFilter: function(d, i){
    return !!/-(on|off|in|out)$/.exec(d);
  },
  disableFilter: function(d, i){
    return /bounce/.exec(d);
  }
});
ldap = new ldAnikitPicker({
  root: '.ldcv',
  defaultFilter: function(d, i){
    return !!/-(on|off|in|out)$/.exec(d);
  },
  disableFilter: function(d, i){
    return /bounce/.exec(d);
  }
});
tgt = document.querySelector('.tgt');
ldcv = new ldCover({
  root: '.ldcv'
});
popupit = function(){
  return ldcv.get().then(function(it){
    return tgt.className = "tgt ld ld-" + it;
  });
};